print("*******************************************")
print("*******************************************")
print("*******************************************")
print("*******************************************")
print("*******************************************")
print(" ")
print("*******************************************")
firstname = input("Enter your first name: ")
lastname = input("Enter your last name: ")
print("*******Welcome to the Flying Circus!*******")
print("Welcome", firstname, lastname)
print("*******************************************")
act = input("What is your circus act?: ")
print("Great! We need more acts like", act)
ability = input("What else can you do?: ")
print("Thanks, so lets confirm....")
print("-------------------------------------------")
print("Your name is", firstname, lastname)
print("Your best act is", act)
print("You can also", ability)
print("Welcome to Monty Python's Flying Circus!")
print("*******************************************")
print("*******************************************")
print("*******************************************")
print("*******************************************")
print("*******************************************")
